apiVersion: v1
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAidXNlcm5hbWUiOiAibW9oYW1lZHNhbGVtNjYiLA0KICAgICAgInBhc3N3b3JkIjogImdocF9LUG1IbWhJSFpxRDRkcXVzdFhrSzlLMmhzZnZPaDg0RlRTc0oiDQogICAgfQ0KICB9DQp9
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
